### ISSUE TITLE
Yahoo preperation changed

### ISSUE THREAD

**Issue by Arria** [deltachat/provider-db#110]
## Basic information (please modify and submit) 

**Domain(s):** Yahoo (the domain part of your e-mail that you tried it with) 

**Website of provider:** yahoo.de

**Does it work without Preparations?** NO

These three points are already useful enough to submit.

But if you can please provide more information below. 

### following preparations from the provider side (please add links if you can): 

- [x] [setting a per-app password](https://help.yahoo.com/kb/account/SLN27791.html)
- [ ] setting an option in provider's web interface 
- [ ] other: please describe 

## Other Comments 

I just helped a friend with the setup of Delta-Chat. She is using a Yahoo Mail Account, and we found that in the account security screen the Option “Allow apps that use less secure sign in” isn't available anymore (in Accounts where the Option is already turned on, this message is showing up: "This option will be going away on June 30, 2020"). 

Now you have to set an “App-Password” in the account security screen instead:
https://help.yahoo.com/kb/account/SLN27791.html

**Comment by angelo-fuchs** [comment]
@r10s Should we inform current DC+Yahoo users that they will have to do something or DC will break on 30th of June?

**Comment by r10s** [comment]
this is not doable from the provider-db in the current state, we can only send messages after configure. therefore, we need to hard-code that to the core, but even then, it is unclear if all users update before June 30.

not sure, however if this is worth the effort. i would also assume that yahoo informs their users about the change.
