### ISSUE TITLE
Outlook should now support DC, with preparation

### ISSUE THREAD

**Issue by parnikkapore** [deltachat/provider-db#128]
Outlook now supports POP and IMAP, at least on the organizational account I'm using. This needs to be turned on in Settings.

The IMAP server also supports IMAP IDLE.

**Comment by missytake** [comment]
Yes, the point why outlook.com is broken is not that they don't offer IMAP, but that they mess with some headers Delta Chat needs: https://providers.delta.chat/outlook-com

For more details, see https://github.com/deltachat/deltachat-core-rust/issues/1006
