### ISSUE TITLE
Add firemail.de

### ISSUE THREAD

**Issue by link2xt** [deltachat/provider-db#133]
Seem to offer email services, though SMTP is for non-free accounts only.

**Comment by r10s** [comment]
even if you pay the [largest packet for 24 €/y](https://firemail.de/E-Mail-Tarife) you can use at most 30 recipients, we should add at least a login-hint pointing to these issues, yes.

i think, this _firemail_ comes from the pre-google, german search-engine _fireball_ - not sure if that is still relevant at all, but at least the page seems to be pretty modern :)
