### ISSUE TITLE
Add cryptix.net

### ISSUE THREAD

**Issue by link2xt** [deltachat/provider-db#134]
Server settings are here:
https://cryptix.net/hilfe/mail/serverdaten/

**Comment by r10s** [comment]
that probably already works out-of-the-box, or?

**Comment by link2xt** [comment]
It should, by I don't know how to get an account.

**Comment by r10s** [comment]
i am hesitating a bit adding info to provider-db that no-one can test and that do not come from some user-request or from users reporting sth. is not working.

**Comment by r10s** [comment]
closing for that reason, see recent irc lines
