### ISSUE TITLE
add Virgilio provider

### ISSUE THREAD

**Issue by ghost** [deltachat/provider-db#146]
## Basic information

**Domain(s):** virgilio.it 

**Website of provider:** www.virgilio.it 

**Does it work without Preparations?** NO

### following preparations from the provider side: 

- [ ] setting a per-app password 
- [ ] setting an option in provider's web interface 
- [ ] other: please describe 

### Server Settings

Do you know which servers the provider uses?

```
    smtp-server: out.virgilio.it
    smtp-port: 465
    smtp-security-socket: SSL

    imap-server: in.virgilio.it
    imap-port: 993
    imap-security-socket: SSL
```

## Other Comments 

How can you register at the provider?

https://registrazione.virgilio.it/

Is there anything else we need to know about the provider?

It is a very fast mailing provider and registration is free.

**Comment by hpk42** [comment]
i failed to register a test address.
could you provide one, maybe send it to holger at deltachat de?

**Comment by AndreazLattmann** [comment]
Ok!
