### ISSUE TITLE
Automatically validate that all listed ports are open

### ISSUE THREAD

**Issue by link2xt** [deltachat/provider-db#156]
For TLS also check that they have valid certificates if `strict_tls` is not `false`.

**Comment by r10s** [comment]
i just talked with @hpk42 about a similar thing - maybe we can add a corresponding check also to the core, checking if STARTTLS/SSL works on the given servers. we could do this in rust or in python, as python does not have the list of all providers, maybe rust is better.

**Comment by link2xt** [comment]
When I wrote this issue I had the JavaScript validation script in mind. The idea is to have validation here in CI, independent of delta chat core.

**Comment by r10s** [comment]
sure, anything on that would be great :)

**Comment by missytake** [comment]
closed in #223 :)

**Comment by r10s** [comment]
yeah!
