### ISSUE TITLE
Add hosting.de Provider

### ISSUE THREAD

**Issue by angelo-fuchs** [deltachat/provider-db#159]
Works with DC: Yes. Out of the box.
As hosting.de is a contracting service one needs to fill out:
- E-Mail Adress
- IMAP Server
- SMTP Server

separately as example@hosting.de is not the mail address of the user, but example@example.com is and the DNS of example.com has an MX that points to hosting.de.

Supports +Mail: Yes. Out of the box.
If used one needs to fill in IMAP-Login and SMTP-Login additionally with the base address.

Supports Server Side filters: Yes. Out of the box (RoundCube).
Login to the Webmail system, Select "... More" Icon -> Create Filter.

I'll need to see how they react to the increased quantity of mails that come with messaging.

**Comment by missytake** [comment]
This provider supports custom domains, which is not supported yet, but will be tackled soon(tm). Will be reopened then.
