### ISSUE TITLE
Add the provider Websupport.se

### ISSUE THREAD

**Issue by havet** [deltachat/provider-db#177]
## Basic information (please modify and submit) 

**Domain(s):** Your own domain ending in e.g. se .nu .eu .com .net .org
**Website of provider:** https://www.websupport.se/

**Does it work without Preparations?** YES

### Server Settings
Depends on your account.
The ports are not the standard ones.

You have to log into the Control panel to display the settings. You´ll find them next to the list of your mail accounts. They are also displayed every time you create a new mail address.

Misc:

You can host and register many types of domains with this provider, not only .se
This provider is a subsidiary to one of the largest Swedish providers (Loopia).

**Comment by missytake** [comment]
Unfortunately we don't have support for custom domains yet, so I don't think it makes much sense to tackle this issue before that.

**Comment by havet** [comment]
I don't understand what's so special with custom domains? The domain has not any impact on the function of Delta Chat, as far as I can see. What's important is how the mail server works.
BTW some of the providers already listed offers custom domains as well.

**Comment by r10s** [comment]
> I don't understand what's so special with custom domains?

we cannot easily derive the provider from a custom domain. however, the provider is needed to file a record here in the provider-db.

in general, there are some possibilities to detect the provider for a custom domain, however, as far as i know, there is no simple method that is "always" working, and it is just not implemented.

therefore, currently, custom-domains just do not work.

> The domain has not any impact on the function of Delta Chat

that's true. the provider-db is just there to prefil some settings.

**Comment by havet** [comment]
Ooh. Got it. You hard code setting for a set of domains (connected to certain providers)? The user will thus not have to manually add servers and ports? Is that the idea? 
In that case I withdraw my suggestion to add Websupport to the list. Lots of hosting services/web hotels etc would serve, but you will have to enter some basic info as for any email client. You might add some info about that somewhere, for users with their own domain(s).

**Comment by r10s** [comment]
k, closing this then, no actionable item left here.
