### ISSUE TITLE
Add Tutanota

### ISSUE THREAD

**Issue by digitalethics** [deltachat/provider-db#178]
Could you add [Tutanota](https://tutanota.com/) to the list at https://providers.delta.chat/ and provide instructions how to set it up? Many thanks!

**Comment by r10s** [comment]
yip, we should add tutanota, good idea.

> and provide instructions how to set it up?

unfortunately, tutanota does not support the usual email standards and eg. does not support imap - so, you just cannot use tutanota with Delta Chat - nor with Thunderbird, Apple Mail, or whatever client :/

cmp. https://delta.chat/en/help#is-delta-chat-compatible-with-protonmail--tutanota--criptext
