### ISSUE TITLE
I.ua doesn't support IMAP thus can't be delta chat supported email provider.

Proof link (in russian):
https://help.i.ua/section/11/

### ISSUE THREAD

**Issue by andros-ua** [deltachat/provider-db#193]
![IMG_20210810_184152.jpg](https://user-images.githubusercontent.com/46114524/129450139-a2836dc9-1017-421a-af96-9702c8369c2e.jpg)

Translation: IMAP is not provided or planned.

**Comment by r10s** [comment]
thanks a lot for taking care - so https://github.com/deltachat/provider-db/blob/master/_providers/i.ua.md is just wrong? wondering if that ever worked, cc @link2xt do you know sth. about this provider by chance?

**Comment by link2xt** [comment]
Looks like it never worked indeed, it was just added in the first batch by @Simon-Laux and it's unlikely that all those providers were tested.

**Comment by Simon-Laux** [comment]
> Name: i.ua 4
State: OK on 2017-12
Preparations: -
Credentials: email+password

https://support.delta.chat/t/provider-overview/56/2

looks like there was something wrong in the original provider overview list
