### ISSUE TITLE
Yandex must be removed from the list of supported providers.

### ISSUE THREAD

**Issue by hhrhhr** [deltachat/provider-db#205]
- Operating System (Linux/Mac/Windows/iOS/Android):
all
- Delta Chat Version:
1.20.3
- Expected behavior:
When sending a message, it must be delivered to the subscriber.
- Actual behavior:
When sending a message, it is SMTP server blocks an account for spam for a 24 hours.
- Steps to reproduce the problem:
Add account created on yandex.*
Send a message to the existing contact to create an encrypted message that cannot be analyzing Yandex's services.
- Logs:
```
2021-09-17T17:39:17.329Z	core/event
WARNING		"DC_EVENT_WARNING"	0	"src\\job.rs:255: SMTP failed to send: Permanent(Response { code: Code { severity: PermanentNegativeCompletion, category: MailSystem, detail: Four }, message: [\"5.7.1 [2] Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1631900360-h4Ajl35YEe-dK78OYi4\"] })"
2021-09-17T17:39:17.340Z	core/event 
WARNING		"DC_EVENT_WARNING"	0	"src\\message.rs:1687: Msg#41 failed: Permanent SMTP error: permanent: 5.7.1 [2] Message rejected under suspicion of SPAM; https://ya.cc/1IrBc 1631900360-h4Ajl35YEe-dK78OYi4"
```

When communicating with tech support of Yandex, it turned out that "our service is not intended to send suspiciously looking messages" ...

**Comment by missytake** [comment]
Many factors can lead to a message being classified as spam, others use yandex successfully afaik. Do you have more insights on what caused the blocking?

**Comment by hhrhhr** [comment]
For several years I used the usual local email client. But as soon as Delta Chat installed on the computer and synchronized it with a smartphone, so immediately got a blocking.
Moreover, the blocking is valid 24 hours, but if the Yandex SMTP server is used at this time, the lock is extended for another 24 hours.

**Comment by Yettte** [comment]
> For several years I used the usual local email client. But as soon as Delta Chat installed on the computer and synchronized it with a smartphone, so immediately got a blocking. Moreover, the blocking is valid 24 hours, but if the Yandex SMTP server is used at this time, the lock is extended for another 24 hours.

we are about to do testing with all providers and so far yandex is working, we'll see what else we find out over the time.

**Comment by ed-asriyan** [comment]
confirm. same issue after 15-20 messages in a chat

**Comment by Durman-chik** [comment]
As of 2026, we are still seeing the same issue with Yandex. Everything works fine with other email providers, but Yandex continues to cause the same deliverability problems. This affects not only new mailboxes, but also warmed-up ones. In other words, the issue does not appear to be limited to mailbox reputation or lack of warm-up — Yandex seems to be specifically flagging or restricting this type of traffic, while the same messages are delivered normally through other providers.
