### ISSUE TITLE
Add infomaniak as provider

### ISSUE THREAD

**Issue by darhma** [deltachat/provider-db#208]
## Basic information 

**Domain(s):** ik.me

**Website of provider:** infomaniak.com 

**Does it work without Preparations?** YES

### following preparations from the provider side (please add links if you can): 

- [ ] setting a per-app password 
- [ ] setting an option in provider's web interface 
- [ ] other: please describe 

### Server Settings

Do you know which servers the provider uses?

```
    smtp-server: mail.infomaniak.com
    smtp-port: 465
    smtp-security-socket: SSL/TLS

    imap-server: mail.infomaniak.com
    imap-port: 993
    imap-security-socket: SSL/TLS
```

## Other Comments 

How can you register at the provider?

You can create a free account (@ik.me) at https://welcome.infomaniak.com/signup/ikmail/steps.

Otherwise you can create a paid account at https://welcome.infomaniak.com/signup/steps.

Is there anything else we need to know about the provider?

I have a free account (@ik.me) and it seems to work without problems and without any special preparation (I honestly don't remember if the IMAP and SMPT server names and port numbers were entered by me or were automatically configured).

**Comment by missytake** [comment]
thanks for the suggestion! I got it working on my side as well.
