### ISSUE TITLE
cock.li blocks users using deltachat

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#21]
Probably because too many messages are sent in their opinion.
In our test we used cock.li for fast email adresses because they only need username and password for registration. unfortunately after sending ~9 messages and recieving 10 message in a timespan of roughly 10 minutes.
So its unusable for deltachat users, we need a new column to represent this case.

**Comment by missytake** [comment]
related: https://support.delta.chat/t/new-provider-db/732

**Comment by r10s** [comment]
not sure if we need a new column or own field. i would go for that only if we really make programmatically use of the info.

i'd add these info to a free-text field, the one that is shown after successful login (and maybe always on the web).

**Comment by r10s** [comment]
and: is really _deltachat_ blocked? or just users with more frequent usages?

**Comment by Simon-Laux** [comment]
no as I stated above you get blocked for sending emails too fast, which is very common when chatting.

**Comment by r10s** [comment]
k, then the title is a bit misleading

**Comment by Simon-Laux** [comment]
yeah I admit its a bit clickbaity

**Comment by pabzm** [comment]
Do you realize what kind of right-wing, racist, and neo-fascist community cock.li is part of? Please drop it, and let's stop caring for it.

Even CCC managed to kick the founder from congress 2019, and they are not exactly quick with that kind of reaction.

**Comment by missytake** [comment]
we took it already out a few weeks ago.
