### ISSUE TITLE
Should we document rate limits?

### ISSUE THREAD

**Issue by bkil** [deltachat/provider-db#213]
Certain providers apply (or even publish) rate limits for outgoing or incoming messages within a certain time frame (per minute, hour or day). When reaching such a limit, they may reject or drop mail or even block the sender for 24 hours or more.

Some of these limits are so low that it could interfere with chats or group chats. Hence it could be a deciding factor when choosing between providers.

**Comment by Yettte** [comment]
> Certain providers apply (or even publish) rate limits for outgoing or incoming messages within a certain time frame (per minute, hour or day). When reaching such a limit, they may reject or drop mail or even block the sender for 24 hours or more.
> 
> Some of these limits are so low that it could interfere with chats or group chats. Hence it could be a deciding factor when choosing between providers.

We are indeed trying to find published rate limits per provider, but many of them are hiding this info saying that they risk more spamming. However, we have also testing scripts trying to find this info anyway. thanks for the idea though!

**Comment by bkil** [comment]
Could you perhaps share where the testing scripts publish their findings?

**Comment by Yettte** [comment]
> Could you perhaps share where the testing scripts publish their findings?

We are still running them and plan to publish the scripts and results at the end on the Delta Chat blog. In the meantime, this might be interesting to you... https://github.com/deltachat/performance-analysis
