### ISSUE TITLE
specify mail servers for providers where it's possible, but slow to guess them

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#217]
riseup.net, systemli.org and disroot.org are three mail providers which usually take very long to login. They don't have autoconfigure files, and they don't have "server" entries in the providerDB, because it's easy to guess their current servers and if they change their settings at some points it was stupid to hardcode them in the first place.

But they also seem to have some DDOS protection in place which makes it very hard to guess their servers. With all three providers, it takes several minutes to login. So it would make sense for those to just enter the server addresses to the providerDB.

riseup.net are quite conservative with mail settings. They know that many of their users add server configuration parameters manually into thunderbird or so. For the other 2 providers I'm not so sure. But still it makes sense to just do this to speed up login.

Thoughts @r10s?

**Comment by r10s** [comment]
i did not know (for forgot ;) that we have a "policy" for that kind of things.

however, yes, if some provider does not have autoconfig and guessing is known to be slow, it makes sense to add the server data.

otoh, if a server has an autoconfig or guessing is fast enough, it is probably better to stay with that - unless there are good reasons not to do so.

**Comment by missytake** [comment]
Right, it's not a *policy* policy :D okay, then I'll just add the server addresses for those 3 providers for now :)

**Comment by r10s** [comment]
at some point, to feel better when adding servers/ports, it would be great if the servers/ports declared here are checked on a regular base. or does that already happen wrt dapsi? 

@missytake if not, as you are more deep into all that, can you maybe file an issue for that if that also makes sense to you?

**Comment by missytake** [comment]
we don't have test accounts for all providers in the DB and it's unlikely we ever have - but @hpk42 and I talked about a daily github.com/deltachat/eppdperf login check with the accounts we have, that would make sense. 

See https://github.com/deltachat/deltachat-core-rust/issues/2963

**Comment by r10s** [comment]
> we don't have test accounts for all providers in the DB and it's unlikely we ever have 

my idea is not to login,  just do everything just before login - if a server/port is invalid, that will probably already fail, or?

**Comment by missytake** [comment]
Hm, true. Should be quite easy:

```
>>> import smtplib
>>> conn = smtplib.SMTP_SSL("dc.develcow.de", "465")
>>> conn = smtplib.SMTP_SSL("dc.develcow.de", "466")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/smtplib.py", line 1043, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "/usr/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.8/smtplib.py", line 1049, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```

**Comment by missytake** [comment]
I started something :) https://github.com/deltachat/provider-db/pull/223
