### ISSUE TITLE
Add information for 1&1 (custom domain)

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#23]

**Comment by JostAusSoest** [comment]
I can confirm that you just have to enter your mail address, password and "imap.1und1.de".

**Comment by Simon-Laux** [comment]
those seem related:
```
imap.ionos.com
smtp.ionos.com
imap.ionos.de
smtp.ionos.de
```

https://www.ionos.com/help/email/other-email-programs/add-a-mail-basic-email-account-to-mozilla-thunderbird/
https://www.ionos.de/hilfe/e-mail/e-mails-auf-android-smartphones-nutzen/e-mail-konto-auf-android-smartphone-einrichten/#

1&1 moved their email/domain stuff to a new site (ionos.com and ionos.de) so we should include those new domains too.

**Comment by missytake** [comment]
We don't add custom providers for now.
