### ISSUE TITLE
Hotmail problems?

### ISSUE THREAD

**Issue by snan** [deltachat/provider-db#235]
Someone I talk to 30000 times per day is on Hotmail, and on my end, I can see messages from both of us, with the padlock. But they can't see my messages and when they tap "Updating" they see this message. This started yesterday. Is this new?

![IMG_0729](https://user-images.githubusercontent.com/309417/160810306-d6889852-3b00-4ace-95a1-7aed58da6bfc.jpeg)

**Comment by snan** [comment]
Normal emails from my other MUA (if I toggle Autocrypt off) do get through.

**Comment by snan** [comment]
The person told me it started working but they needed to delete my messages from the last few days. Still have no idea what was going on. Feel free to reopen.

**Comment by missytake** [comment]
Hm, no idea either. But your profile picture is looking raaad

**Comment by gerryfrancis** [comment]
Probably related: https://github.com/deltachat/deltachat-core-rust/issues/2727
