### ISSUE TITLE
Add 163 Mail

### ISSUE THREAD

**Issue by Micraow** [deltachat/provider-db#236]
## Basic information (please modify and submit) 

**Domain(s):** 163.com (the domain part of your e-mail that you tried it with) 

**Website of provider:**  mail.163.com

**Does it work without Preparations?** Doesn't work at all

These three points are already useful enough to submit.

But if you can please provide more information below. 

### following preparations from the provider side (please add links if you can): 

- [x] setting a per-app password 
- [ ] setting an option in provider's web interface 
- [ ] other: please describe 

### Server Settings

Do you know which servers the provider uses?

```
    smtp-server: smtp.example.com
    smtp-port: 25/465/587...
    smtp-security-socket: SSL/STARTTLS

    imap-server: imap.example.com
    imap-port: 993/143...
    imap-security-socket: SSL/STARTTLS
```

## Other Comments 

How can you register at the provider?

Is there anything else we need to know about the provider?

 163 mailbox, the most popular mailbox in China, has the widest user group (many people even think of 163 mailbox when they think of mailbox), and it is very fast.however, Delta Chat doesn't support it. The reason is that it needs an "IMAP ID". I don't think it seems to be a very troublesome thing. Can the developers of delta chat make efforts to make 163 mail available?

**Comment by missytake** [comment]
This seems to need changes to the core, instead of the provider database. It seems that we have to support the [IMAP4 ID capability](https://www.ietf.org/rfc/rfc2971.txt), I'm not sure if we already do that.

This comment is very helpful in that regard: https://github.com/deltachat/provider-db/pull/187#issuecomment-869137851, linking it here for reference.

I quickly translated the [163.com documentation about the issue](https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac211b1978002df8b23) to english with deepl.com:

> When you use IMAP protocol to receive emails, for the security of user accounts, the system requires your client to indicate the relevant "identity" information in order to allow connections.
> 
> Otherwise, the following error will be returned: Unsafe Login. Please contact kefu@188.com for help
> 
> You will also receive a reminder email in your mailbox, as shown below.
> 
> Commonly used clients such as Outlook, foxmail, mailbox master will not have this kind of problem.
> 
> If you are using a client that is unable to receive due to this limitation. Please contact the software developer to update the relevant source code and bring the IMAP ID information when connecting to the server. The relevant JAVA sample code is as follows: (For other languages or frameworks, please contact the corresponding developers to deal with them, NetEase only provides JAVA language sample code.)
> 
> ```
> Properties props = new Properties(); 
> props.setProperty("mail.store.protocol", "imap"); 
> props.setProperty("mail.imap.host", "imap.163.com"); 
> props.setProperty("mail.imap.port", "143"); 
> 
> HashMap IAM = new HashMap();
> //bring IMAP ID information, consisting of key and value, such as name, version, vendor, support-email, etc.
> IAM.put("name", "myname");      
> IAM.put("version", "1.0.0");      
> IAM.put("vendor", "myclient");      
> IAM.put("support-email", "testmail@test.com");  
> Session session = Session.getInstance(props); 
> 
> IMAPStore store = (IMAPStore) session.getStore("imap");
> //replace the corresponding account and authorization code below
> store.connect("testmail@163.com", "password"); 
> 
> store.id(IAM);
> ```
> 
> For links to related specifications please refer to.
> https://www.ietf.org/rfc/rfc2971.txt
> https://javaee.github.io/javamail/docs/api/index.html?com/sun/mail/imap/IMAPStore.html
> (Please use JavaMail version 1.5.1 and newer)

**Comment by missytake** [comment]
It would be very helpful to have a 163.com test account to be able to test this. @Micraow @yhh2021 can you maybe provide a test account for us? You can message me at missytake@systemli.org.

**Comment by r10s** [comment]
what is unclear to me:

- can we just use any `name`, `version`, `vendor` and `address`  
or do we need to register somewhere at 163.com or at some authority?

**Comment by r10s** [comment]
@link2xt can you tell if IMAP ID as of https://www.ietf.org/rfc/rfc2971.txt is somehow supported by our core stack? or what would be needed?

**Comment by Micraow** [comment]
> what is unclear to me:
> 
>     * can we just use any `name`, `version`, `vendor` and `address`
>       or do we need to register somewhere at 163.com or at some authority?
> 
> 
> cc @Micraow @yhh2021

I just reread the document.I think there may be more information.
![IMG_20220621_164205](https://user-images.githubusercontent.com/48644801/174757451-9d70b8e3-b508-41dd-861e-1dcc00b4d24c.jpg)

There should be at least the above information.

**Comment by Micraow** [comment]
> > can you tell if IMAP ID as of https://www.ietf.org/rfc/rfc2971.txt is somehow supported by our core stack? or what would be needed?
> 
> Sending ID should be added to async-imap. Parser already supports this extension: https://github.com/djc/tokio-imap/blob/f0105b772eca9895a4d6aeace5e7caee96641881/imap-proto/src/parser/rfc2971.rs

Great! I wonder if we can use it.

**Comment by r10s** [comment]
> Interesting, it supports XAPPLEPUSHSERVICE, but not IDLE:

this seems to be a good test to check if out fake-IDLE (using polling) is still working :)

**Comment by missytake** [comment]
1.32.0 is released, at least for android and iOS. Did anyone have the chance to try that out? If yes, feel free to close the issue again :)

**Comment by Micraow** [comment]
> 1.32.0 is released, at least for android and iOS. Did anyone have the chance to try that out? If yes, feel free to close the issue again :)

Hello,  I am Micraow. 
I have tested the latest version today. 
Above all,  I want to thank you for your help. I can login 163 email now. It can connect to the DeltaChat folder and get the mail at present. It can also send emails. 
However,  there is a confusion problem.  Delta Chat cannot connect to the root folder and download emails. 

I wonder why? I didn't get warnings from 163 Mail. It seems that 163 Mail didn't block the request. 

Thank you for your continuous attention!

**Comment by Micraow** [comment]
Yes. I'm sure that I have enabled this option.
Just now， I woke up. And surprisingly, I found that Delta Chat  worked well. It can now receive emails from root directory ,without any changes.


> > However, there is a confusion problem. Delta Chat cannot connect to the root folder and download emails.
> 
> Have you enabled the option "Show Classic E-mails"? It's disabled by default.

**Comment by missytake** [comment]
Great! Thanks for helping with fixing this for everyone :)

**Comment by r10s** [comment]
@Micraow and all - thanks a lot for making 163 finally working 🙏

**Comment by Goojoe** [comment]
Now I use 163.com email and can use Delta Chat to send emails to others, but I cannot receive Delta Chat emails. It says that the emails are blocked by the client.

**Comment by missytake** [comment]
> Now I use 163.com email, and I can use Delta Chat to send emails to others, but I cannot receive emails from other Delta Chat clients. Even if I add the sender to the whitelist, 163.com will still block the email.

can you forward a rejected email to <af81vllxk94pje1wdjx9wt7b@systemli.org>?
