### ISSUE TITLE
better repo name

### ISSUE THREAD

**Issue by hpk42** [deltachat/provider-db#27]
i suggest to rename this repo to "provider-db" -- this is really about providing/establishing a collaborating database that is then used by deltachat to have a better setup process.  There also are other community-run efforts like protondb or steamdb (https://steamdb.info) to collect info.  The "overview" is more the web page which is also part of this repo, but the core functionality of it is being a machine-readable database with contributions from users.

**Comment by Simon-Laux** [comment]
I renamed it
