### ISSUE TITLE
update gmail.com description

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#274]
## Someone reported this:

Kleine Info: Die Methoden die bei Delta stehen damit Gmail geht sind scheinbar outdatet. GMail sagt dazu:

> Zum besseren Schutz Ihres Kontos unterstützt Google ab dem 30. Mai 2022 keine Drittanbieter-Apps oder ‑Geräte mehr, bei denen Ihr Nutzername und Passwort ausreichen, um sich in Ihrem Google-Konto anzumelden.
> 
> Wichtig: Diese Frist gilt nicht für Kunden von Google Workspace oder Google Cloud Identity. Das Datum des Inkrafttretens dieser Richtlinie für diese Kunden wird zu einem späteren Zeitpunkt im Workspace-Blog angekündigt.

Bei der Einstellung die man laut Delta anmachen soll steht "Diese Einstellung ist für Ihr Konto nicht verfügbar."

also hier steht mehr auf englisch: [https://providers.delta.chat/gmail](https://github.com/deltachat/provider-db/issues/new#)
Aber ich hab den Eindruck, dass das outdated ist, zumindest Variante 3.

## to do

Re-check how gmail.com IMAP & SMTP can be activated.

**Comment by r10s** [comment]
we are describing how to set up app-specific passwords, this was recently updated, https://providers.delta.chat/gmail

it was somehow forgotten to close this issue, however :) thanks for taking care!
