### ISSUE TITLE
Rework Registration:Personal Data value

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#28]
- Rename to identification
- change from boolean to array of kinds of identification (phonenumber / postal-address / another email address / passport / etc. )
- remove seperate phonenumber column

**Comment by r10s** [comment]
we sorted out the things we want to file at https://support.delta.chat/t/new-provider-db/732/6 - at least for now, we decided to not to collect information about phonenumber / postal-address / another email address / passport usage of the providers - although this would probably very interesting.
