### ISSUE TITLE
While testing mehl.store.md...

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/provider-db#281]
Test failed, exerpt of the log:

Error:  c3.testrun.org:993... [error] ConnectionRefusedError: [Errno 111] Connection refused
Error:  c3.testrun.org:465... [error] ConnectionRefusedError: [Errno 111] Connection refused
Error: Process completed with exit code 2.

But shall it test not the host of the new provider????

**Comment by missytake** [comment]
It tests the hosts of the new provider, but all the others as well. This makes us aware if another provider vanishes. In this case, c3.testrun.org was down, now it passes again.

I thought about only running the job on pushing to the master branch (i.e. merging a PR), but that would mean that we don't test the new PRs... and finding out which providers are new and only testing those has its own complications. For now it is fine to always test all of the providers in every PR, even if they aren't modified.
