### ISSUE TITLE
`strict_tls` moved to `opts`?

### ISSUE THREAD

**Issue by WofWca** [deltachat/provider-db#285]
I see 3c8f7e846c915a183dc44536fb5480d1f25d7c42 moved it to `opts`, but it's still not removed from top-level from

https://github.com/deltachat/provider-db/blob/3c8f7e846c915a183dc44536fb5480d1f25d7c42/validation/index.js#L87

and

https://github.com/deltachat/provider-db/blob/8d3ce6d1f3e6bde1e6d092849184e1d2ebe961c9/README.md#L45

Also some providers still specify it at top-level, namely these two recently added ones:

https://github.com/deltachat/provider-db/blob/5b35f7b87103fa0895fdc471769386113371688d/_providers/mehl.cloud.md#L17

https://github.com/deltachat/provider-db/blob/5b35f7b87103fa0895fdc471769386113371688d/_providers/daleth.cafe.md#L17

Is it ok or nah?

**Comment by iequidoo** [comment]
It's not ok, i forgot to remove `strict_tls` from https://github.com/deltachat/provider-db/blob/3c8f7e846c915a183dc44536fb5480d1f25d7c42/validation/index.js#L87 and https://github.com/deltachat/provider-db/blob/8d3ce6d1f3e6bde1e6d092849184e1d2ebe961c9/README.md#L45 and that's the reason why it appeared in the new provider files. So, it should be removed from there (although that actually changes nothing)

**Comment by WofWca** [comment]
Ok, I can make an MR later today probably.

**Comment by WofWca** [comment]
Oh, you already assigned. Never mind.
