### ISSUE TITLE
imap test failed.

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/provider-db#292]
Pull-Request - auotmated Test - Network not reachable...

Don't know, why...

> Installing collected packages: pyyaml

> Successfully installed pyyaml-6.0.1

Error:  

> c3.testrun.org:993... [error] OSError: [Errno 101] Network is unreachable

> Error:  c3.testrun.org:465... [error] OSError: [Errno 101] Network is unreachable

> Error: Process completed with exit code 2.

**Comment by missytake** [comment]
Let's remove c1-c3.testrun.org from providerDB. They are just testing machines, they are supposed to fail every once in a while.
