### ISSUE TITLE
Style Provider List Page

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#3]
That it looks good:

- [x] don't show auth column in the table on index.html
- [x] table only on the right half of the page
- [x] status column with nicer colors and shorter, white letters
- [ ] different ranking algorithm: popular and working providers to the top
- [ ] sort providers by name, status, or domains
- [x] drop date in the status column
- [x] better mobile view
- [x] explanation text for index.html
- [x] footer with disclaimer and link to delta.chat

**Comment by Simon-Laux** [comment]
Probably also add some descriptions for the column headers that work on mobile.

**Comment by Simon-Laux** [comment]
> Probably also add some descriptions for the column headers that work on mobile.

Because at the moment it's using the `title=""` attribute that show a description on hover.

**Comment by missytake** [comment]
If we want to rank the providers differently than alphabetically, we could rank them by their SEO popularity. It's of course not accurate, and ethically questionable, but this tool here just gives a rough estimate how many people use google to search for a term: 

https://serpstat.com/keywords/?se=g_de&search_type=keyword&query=provider

If we don't really show the number, but just use it to rank the providers in the table, more users would find their provider on first glance.

2 problems with this approach:

- serpstat divides up search results by country; I didn't see an option to show global search results.
- this makes the monopolies stronger, and keeps the peripheries in the periphery.

A second factor for the ranking should be how well the provider works, (e.g. OK vs. PREP, but maybe in the future also performance benchmarks).

**Comment by missytake** [comment]
Another thing: while I like having colored boxes for the status column, it's now to obvious on the first glance that "PREPARE" is a clickable link. If we show this information in-app, it doesn't matter much; another approach would be 

```
.status-prep {
  color: var(--color-prep);
  background: white;
  padding-left: 5pt;
  text-decoration: none;
}
```

**Comment by Simon-Laux** [comment]
how about a hover/focus style?

**Comment by r10s** [comment]
i think we can revisit this as needed.
