### ISSUE TITLE
Outlook: hard requirement on oauth2

### ISSUE THREAD

**Issue by AeliusSaionji** [deltachat/provider-db#306]
https://support.microsoft.com/en-us/office/modern-authentication-methods-now-needed-to-continue-syncing-outlook-email-in-non-microsoft-email-apps-c5d65390-9676-4763-b41f-d7986499a90d

Deltachat is now entirely incompatible unless/until oauth2 support is added.

**Comment by iequidoo** [comment]
Thanks for the news, i cited your message in [3196](https://github.com/deltachat/deltachat-core-rust/issues/3196), the main discussion is there
