### ISSUE TITLE
Outlook.com requires OAuth 

### ISSUE THREAD

**Issue by havet** [deltachat/provider-db#309]
domain-part of e-mail address:
outlook.com

](https://www.microsoft.com/sv-se/microsoft-365/outlook/email-and-calendar-software-microsoft-outlook?market=se)

**Does it work without Preparations?** NO, account will be unusable without OAuth from september 16, 2024

Got this e-mail notice twice (Swedish):
"<html>
<body>

Den 16 september 2024 kommer appar som använder mindre säker inloggningsteknik inte längre att kunna komma åt din e-post.
--
Att skydda din information är högsta prioritet för Microsoft. För att skydda ditt konto kommer Microsoft inte längre att stödja användningen av e-post- och kalenderappar från tredje part där du loggar in enbart genom användarnamn och lösenord för ditt Microsoft-konto. Genom att använda en e-post- eller kalenderapp som stöder Microsofts moderna autentiseringsmetoder får du ett bättre skydd. Om du inte ordnar detta kommer dina e-postappar från tredje part från den 16 september 2024 inte längre att kunna komma åt din e-postadress i Outlook.com, Hotmail eller Live.com.Det här måste du göraOm du får det här e-postmeddelandet använder du för närvarande en e-post- eller kalenderapp som ansluter till ditt Outlook.com-e-postkonto genom en mindre säker autentiseringsmetod. Du måste uppgradera din e-post- och kalenderapp från tredje part till en version som stöder moderna autentiseringsmetoder.

</body>
</html>

**Comment by iequidoo** [comment]
Duplicate of #306. Please follow the main discussion at https://github.com/deltachat/deltachat-core-rust/issues/3196
