### ISSUE TITLE
Yandex missing oauth2

### ISSUE THREAD

**Issue by MIntrovrt** [deltachat/provider-db#34]
simon says, yandex should work with oauth2, although he hasnt tried it.

**Comment by missytake** [comment]
I don't understand russian and can't create an account to test it. @link2xt do you know whether yandex.ru works currently?

**Comment by Simon-Laux** [comment]
In the meanwhile I have tried yandex with an appassword. It worked flawlessly.
@missytake they also have an english interface.

**Comment by r10s** [comment]
we tested yandex at some point, yes. but _i_ did not tested it the last weeks. but it is pretty easy (compared to google or gmx ;) to create a yandex account for testing.

**Comment by r10s** [comment]
the current structure https://support.delta.chat/t/new-provider-db/732/6 does not include oauth2 for now (oauth2 needs extra-special handling in the apps anyway).
