### ISSUE TITLE
todo BEFORE release

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#37]
Array with options like:
- inviteOnly
- Mobile number📞
- Postal Address

**Comment by missytake** [comment]
It would also be good to have information on how many people look for the mail provider via search engines. serpstat.com is a good website to find that out; we could save the search volume when we enter the provider into the page and rank them for popularity afterwards.

**Comment by Simon-Laux** [comment]
Don't display domains to the user, have it as machine readable field and use it only in the search

**Comment by missytake** [comment]
If the provider and the domain don't match, like with email.de (which belongs to web.de), wouldn't users be confused? or do we want to use a separate row for each domain which doesn't fit to the provider name?

**Comment by Simon-Laux** [comment]
No, they usually know where they have their account.

**Comment by missytake** [comment]
related: https://support.delta.chat/t/new-provider-db/732

**Comment by r10s** [comment]
closing this issue, the current structure and fields are in https://support.delta.chat/t/new-provider-db/732/6
