### ISSUE TITLE
add port, server, security etc. settings

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#42]
there should be a way to get `mail_server`, `mail_port`, `mail_user`, `send_server`, `send_user` `send_port`, `server_flags` etc. from the provider-db.

this way, we can skip checking the thunderbird database and save at least one http-request.

and we can tweak settings eg. for nauta.

this is a required preparation before #33 can be targeted.

**Comment by Simon-Laux** [comment]
+ security (tls/ssl)

**Comment by r10s** [comment]
also, i think, we should make the advices to be shown _before_ login shorter and just add things that are absolutely neccessary for logging in. maybe we should have a field `preparation_hints` or so. this field should not contain markdown for now, it is not easily displayed, we can allow that later.

in addition to that, we can have a broader `after_login_hints` that can contain hints as "with this provider you can only send 100 messages per day" or so. we could add this to the device-chat then.  
also this should not contain markdown for now as we just do not support this in the frontends.

i know, that markdown is also readable in ascii mode, however, esp. things as urls and headlines are a bit ugly. in general, i would do as few as possible for now.

**Comment by missytake** [comment]
related: https://support.delta.chat/t/new-provider-db/732

**Comment by pabzm** [comment]
I don't know what `mail_user`, `send_user`, etc. are. In #52 I just added some technical details to one page, is that how you imagined it?

**Comment by r10s** [comment]
mail_user is the username that shall be used for imap, send_user is the username that shall be used for smtp.

usually, we do not know them, however, they may be set to sth. as `%EMAILLOCALPART%` or `%EMAILADDRESS%` - this is how the thunderbird database uses it and i think this makes sense.

**Comment by r10s** [comment]
we sorted that out in https://support.delta.chat/t/new-provider-db/732/6 , the README needs an update, however, #58
