### ISSUE TITLE
use two free-text-fields, one longer can go to the device-chat

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#44]
i think, we should make the advices to be shown before login shorter and just add things that are absolutely neccessary for logging in. maybe we should have a field preparation_hints or so. this field should not contain markdown for now, it is not easily displayed, we can allow that later.

in addition to that, we can have a broader after_login_hints that can contain hints as "with this provider you can only send 100 messages per day" or so. we could add this to the device-chat then.
also this should not contain markdown for now as we just do not support this in the frontends, but this is a separate issue.

**Comment by missytake** [comment]
related: https://support.delta.chat/t/new-provider-db/732

**Comment by pabzm** [comment]
I added one example in #52, used `before_login_hint` and `after_login_hint`. Would that meet your expectations?

**Comment by r10s** [comment]
yip, this is exactly what i was thinking about :)

**Comment by r10s** [comment]
we sorted that out at https://support.delta.chat/t/new-provider-db/732/6 , however, the README needs some update.
