### ISSUE TITLE
avoid markdown

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#45]
we should avoid markdown whereever possible for now. 

the different uis do not support it and start supporting markdown opens a lot of possible issues and cornercases to think about.
also, the idea is to put some infos to device-chat - also here, messages currently do not support markdown.
seeing things badly formatted in the different uis can easily be considered as a bug, 

links should be added just as plain text, android and ios already makes them clickable at least in messages. this also has the advantage that the user can "see" the link and type it in on another device.

**Comment by Simon-Laux** [comment]
the question is what parts are website and what parts are website.
IMO we could use plain yaml files without markdown and render the website from them and also parse them for the cargo package.

**Comment by missytake** [comment]
related: https://support.delta.chat/t/new-provider-db/732

**Comment by pabzm** [comment]
As far as I understood, we want to avoid markdown in the structured data (the front-matter part of each file). The content part can contain markdown as it is rendered by jekyll for the web.

**Comment by r10s** [comment]
> The content part can contain markdown as it is rendered by jekyll for the web.

yip, as we have now sorted out which parts are for the apps (the frontmatter) and which for the web (the body), and as markdown in the frontmatter is somewhat unusual, i think we can close this issue.
