### ISSUE TITLE
Add OVH Provider

### ISSUE THREAD

**Issue by AndreasLattmann** [deltachat/provider-db#46]
# Basic information

**domain(s)**: ga-2.it 

**website of provider**: www.ovh.it

**works without preps**: NO 

### following preparations from the provider side: 

- [ ] setting a per-app password 
- [x] setting an option in provider's web interface 
- [ ] other: please describe 

### following advanced settings need to be set

neccessary manually typed advanced settings:

    smtp-server: ssl0.ovh.net
    smtp-port: 993
    smtp-security: SSL/TLS
    imap-server: ssl0.ovh.net
    imap-port: 465
    imap-security: SSL/TLS

### provider is funded by 
- [ ] advertisements 
- [x] recurring payments 
- [ ] donations 
- [ ] private/pro-bono for friends 

## other comments 

With OVH, there are problems receiving emails with Delta Chat.

**Comment by missytake** [comment]
see comments in #50

**Comment by missytake** [comment]
Can you elaborate, which problems there are with receiving mails?

And do you maybe have a screenshot of the provider's settings, where one can see how to turn on IMAP/SMTP?
