### ISSUE TITLE
Crate: include full URL to provider page in provider data.

### ISSUE THREAD

**Issue by pabzm** [deltachat/provider-db#51]
The rust-crate should provide the structured data for each provider as a JSON-encoded string. That is easier to use for the library consumers and more flexible than native structs.

The page content should be rendered and served as web-page, that can be linked to from the Apps. For that purpose the create should also provide a fully qualified URL to that page.

**Comment by Simon-Laux** [comment]
I disagree with the output json part. I believe giving out structs that can be serialized with serde gives us the easiest interface while allowing to serialize into json or another of serde"s supported formats.

**Comment by Simon-Laux** [comment]
Also the url was half saved in it already,
though I agree its better to safe the full one.

**Comment by pabzm** [comment]
You're right. I didn't express correctly what i mean.

What I actually meant is that the apps receive all relevant data for the respective provider from the core at once, JSON-encoded. We'd like to not fetch every single piece of information from different getters of the C-style API.

**Comment by Simon-Laux** [comment]
that's already the case see https://github.com/deltachat/deltachat-core-rust/pull/1076

**Comment by pabzm** [comment]
Great, I missed that! Thank you for the pointer!

**Comment by r10s** [comment]
the uis get the URL by [dc_provider_get_overview_page()](https://c.delta.chat/classdc__provider__t.html#ab32fc5beb439838a16dee3c3160e0f03); this returns the full url then.
