### ISSUE TITLE
add nice texts for gmx.de and web.de

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#56]
i think, both need imap enabled.

for web.de, we should also tell the user to switch of his "inbox sorting". not sure what exactly this was, i think we need to create a test account and try out.

**Comment by Simon-Laux** [comment]
The inbox sorting is that the emails from new contacts are moved to an "unknown sender" imap folder.

Am 23. Januar 2020 23:20:13 MEZ schrieb bjoern <notifications@github.com>:
>i think, both need imap enabled.
>
>for web.de, we should also tell the user to switch of his "inbox
>sorting". not sure what exactly this, was, i think we need to create a
>test account and try out.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/provider-db/issues/56

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by missytake** [comment]
@pabzm The last paragraph in https://github.com/deltachat/provider-db/blob/master/_providers/gmx.net.md talks about web.de - do you remember whether you wanted to write gmx, or whether it's in the wrong file?

**Comment by pabzm** [comment]
I copied that sentence from the old page, should be fixed!

**Comment by pabzm** [comment]
Or better: should be checked if it's still correct first...

**Comment by pabzm** [comment]
Actually I compiled that sentence out of cues from the old information. Don't know why "web.de" slipped in there.

https://hilfe.gmx.net/email/ordner/ordner-verwalten.html explicitly says, that "GMX FreeMail" only allows 20 folders, so we can change that sentence to more concrete wording.

**Comment by pabzm** [comment]
https://hilfe.web.de/email/ordner/ordner-verwalten.html says, web.de allows 40 folders in unpaid accounts, so a similar text could be added to web.de's dataset as well.

**Comment by missytake** [comment]
Added it :)

**Comment by Simon-Laux** [comment]
Idea: Maybe we could use a trouble shooting style for such things:
```md
## [problem worded as question]
[answer]
```
```md
## Why doesn't DeltaChat move its emails to the DeltaChat folder 
Make sure that you created the deltachat folder, Deltachat can only create the folder on its own when the folder limit of 20 (web.de) isn't reached yet.
If you still have this problem reach out to us on our forum.
```
But maybe that's better a general FAQ -> Troubleshooting section/site.
