### ISSUE TITLE
add nauta

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#57]
preparations are not needed, but some special server settings, cc @adbenitez 

currently hardcoded stuff that will be removed:

```
    if param.addr.ends_with("@nauta.cu") {
        let mut p = LoginParam::new();

        p.addr = param.addr.clone();
        p.mail_server = "imap.nauta.cu".to_string();
        p.mail_user = param.addr.clone();
        p.mail_pw = param.mail_pw.clone();
        p.mail_port = 143;
        p.imap_certificate_checks = CertificateChecks::AcceptInvalidCertificates;

        p.send_server = "smtp.nauta.cu".to_string();
        p.send_user = param.addr.clone();
        p.send_pw = param.mail_pw.clone();
        p.send_port = 25;
        p.smtp_certificate_checks = CertificateChecks::AcceptInvalidCertificates;
        p.server_flags = DC_LP_AUTH_NORMAL as i32
            | DC_LP_IMAP_SOCKET_STARTTLS as i32
            | DC_LP_SMTP_SOCKET_STARTTLS as i32;

        info!(context, "found offline autoconfig: {}", p);
        Some(p)
    } else {
```

**Comment by missytake** [comment]
Does nauta.cu have a website? It's not reachable from my ip address at least.

**Comment by missytake** [comment]
How to best represent the "accept invalid certificates? I tried with `socket: NONE` for now.

**Comment by r10s** [comment]
> How to best represent the "accept invalid certificates?

we do not have that defined yet, but nauta uses the default (lazy, accept), so maybe it is not needed.

i think, we can add a `certificate_checks: strict` add add that to selected providers at some point.

**Comment by adbenitez** [comment]
> Does nauta.cu have a website? It's not reachable from my ip address at least.

@missytake  https://webmail.nauta.cu/

**Comment by adbenitez** [comment]
@r10s the issue with nauta was the certificate key, that was the reason why certificate checks where disabled in code for nauta, because even if user set certificate checks to "allow invalid" core still failed with nauta, was that issue resolved??? otherwise login with nauta will be impossible if you remove the hardcoded code

**Comment by r10s** [comment]
AcceptInvalidCertificates is still the default, see https://github.com/deltachat/deltachat-core-rust/blob/e936549446e862c3ba4df6b5feeceb7056514fbf/src/configure/mod.rs#L481

**Comment by adbenitez** [comment]
it is not about accepting invalid certificates, as I said, even manually setting to accept invalid certificates rustTLS(or something like that) failed because the key size was incompatible, don't know if this is still current an issue so please sorry if this is no longer an issue.

**Comment by r10s** [comment]
this should not have been changed by the provider-db. and, of course, we will do test versions as usual. but i am pretty sure nauta will work as before :)

**Comment by adbenitez** [comment]
awesome, looking forward to test it, the provider-db feature looks really cool, this will help a lot users to get started
\o/
