### ISSUE TITLE
how to handle the existing providers?

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#59]
there are currently some dozend providers of different importance in the _providers directory.

as we want to have a nicer, user facing language as @pabzm pointed out in the example at https://github.com/deltachat/provider-db/pull/52 , and this requires quite some work, testing etc., i suggest to move all the existing providers away and start from scratch, after we've settled the README #58 

i think we should start with the providers in the issue tracker then, these are some of the currently most important providers for us, and they should have nice texts and a nice webpage.  
i would also start with very few providers to get some sort of reference, to define the level of quality we expect.

**Comment by pabzm** [comment]
#52 includes moving all yet-unchanged provider pages into the "old" subdirectory. Once you confirm that the meta data format held through the reference implementation in android we can modify those files one by one and move them back to the upper directory. (All pages with `state: OK` will only need the meta data, which is done quickly. Only the few other provider pages need text work.)
