### ISSUE TITLE
update script to the new structure

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#60]
**before this issue can be tackled, https://github.com/deltachat/deltachat-core-rust/pull/1207 has to be ready (without WIP state)**

the current script is written in rust, however, as it needs some larger adaptions, maybe it is easier to rewrite it in python. python has the advantage that there are much more people who can maintain it and take care for that.

the script should just convert the yaml to a .rs source code, maybe just take the destination file as a parameter. we agreed on that we do not want a crate for now, this gets too complicated to handle, developing is slowed down, and we do not want to take care for a crate currently.

**Comment by Simon-Laux** [comment]
What speaks against using nodejs?

Am 24. Januar 2020 01:04:28 MEZ schrieb bjoern <notifications@github.com>:
>**before this issue can be tackled,
>https://github.com/deltachat/deltachat-core-rust/pull/1207 has to be
>ready (without WIP state)**
>
>the current script is written in rust, however, as it needs some larger
>adaptions, maybe it is easier to rewrite it in python. python has the
>advantage that there are much more people who can maintain it and take
>care for that.
>
>the script should just convert the yaml to a .rs source code, maybe
>just take the destination file as a parameter. we agreed on that we do
>not want a crate for now, this gets too complicated to handle,
>developing is slowed down, and we do not want to take care for a crate
>currently.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/provider-db/issues/60

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Simon-Laux** [comment]
Maybe have the script inside of the core repo and it pulls in the git dependency or a specified folder to generate it. That way it could be easier to integrate it in a release cycle.

Am 24. Januar 2020 01:04:28 MEZ schrieb bjoern <notifications@github.com>:
>**before this issue can be tackled,
>https://github.com/deltachat/deltachat-core-rust/pull/1207 has to be
>ready (without WIP state)**
>
>the current script is written in rust, however, as it needs some larger
>adaptions, maybe it is easier to rewrite it in python. python has the
>advantage that there are much more people who can maintain it and take
>care for that.
>
>the script should just convert the yaml to a .rs source code, maybe
>just take the destination file as a parameter. we agreed on that we do
>not want a crate for now, this gets too complicated to handle,
>developing is slowed down, and we do not want to take care for a crate
>currently.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/deltachat/provider-db/issues/60

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Simon-Laux** [comment]
We should have providers in the new structure ready before starting this.

**Comment by r10s** [comment]
i think python is pretty widely used for various purposes by various people in delta, so this seems more natural and lowers barriers. also, also, the installation of node.js seems to be a bit more effort where python is usually just there (took me eg. some time to get the [ios convertTranslations.js](https://github.com/deltachat/deltachat-ios/blob/master/tools/convertTranslations.js) to run).

maybe we should create the script in the core-repo, btw. currently, there is `src/provider.rs` that contains some code and little data - i want to move the data to the then generated file `src/provider_data.rs` - and having a `src/provider_data_update.py` seems pretty easy to understand. also the generator and the target format are in the same repo then. `src/provider_data_update.py` could take a path to a dir with the yaml-files as an argument. this way one could also play around pretty nicely.

**Comment by pabzm** [comment]
I support putting the script into the core-repo. And I support using python:there's already python-scripts in the core-repo but no node.js so far, we shouldn't introduce it without a very good reason.

**Comment by r10s** [comment]
after some irc with @dignifiedquire and @flub - maybe it is simpler to keep the current generation in rust and adapt it to the new needs (there were other arguments i forgot :)

this would have the advantage of more or less automated updates.

let's wait until the rust structure is settled and decide on that then.

**Comment by r10s** [comment]
done in https://github.com/deltachat/deltachat-core-rust/pull/1207
