### ISSUE TITLE
GitHub action to check the YAML format for new providers

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#61]
When someone opens a PR for adding a new provider, we want to have a github action to check some things:

- [x] Check YAML syntax with lint or so
- [x] If status == PREPARATION, does before_login_hint exist?
- [x] If status == PREPARATION, does markdown exist? (maybe even require screenshots?)
- [x] If status == BROKEN, does before_login_hint & after_login_hint exist?
- [x] Push to GitHub checks to notify contributors

Other ideas what we could check?

**Comment by Simon-Laux** [comment]
for reference our old checks are in
https://github.com/deltachat/provider-db/blob/20d850a511350be61de56bb9ca00980ccba7a4ef/build.rs#L59-L91

**Comment by r10s** [comment]
> Other ideas what we could check?

just a suggestion:

to not get a mix of specified data and guessed data (where guessing may change and/or may take time for probing), we could make sure that, if a server is given, that should be exhaustive.

so all of protocol, hostname, port, socket (not sure if the latter is needed at all, but, we have it everywhere currently). also at least two servers, imap+smtp server, should be specified.

username_pattern, however, is optional and defaults to the email-address.
