### ISSUE TITLE
state or status?

### ISSUE THREAD

**Issue by r10s** [deltachat/provider-db#63]
https://english.stackexchange.com/questions/12958/status-vs-state

the api uses _status_, the yaml _state_ - i won't mind, but it is easier if we use the same everywhere.

**Comment by Simon-Laux** [comment]
yaml uses state because it was a subkey of `status`, which also contained the last update date of that status.
So it's a relic of past times and we can change it back to `status`.

**Comment by r10s** [comment]
the api was also dc_provider_get_status(), but we can rename that, np.
