### ISSUE TITLE
What to do with providers who only offer custom domains?

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#71]
For example in #46 we have a provider which offers only custom domains for its users. This means there is no case, in which the server settings will be recommended in the app. How do we want to deal with this? I see several options:

* Add a long list of custom domains from all the users who approach us that they use this provider
* Don't include the entries into the app at all, as @Simon-Laux suggested in #50 
* Detect the custom provider with DNS queries in the core, as @Simon-Laux suggested in #50 

Opinions?

**Comment by Simon-Laux** [comment]
First option 2 (`Don't include the entries into the app`) later option 3 (Detect the custom provider with DNS queries) but that will require us to add a mailserver-domains-array property next to the domains.

There is another thing regarding dns in the core -> find the autoconfig xml when its location is mentioned in the dns entries of that domain. But this action isn't dependent on the provider-db.
I wrote this clarity in hope to prevent confusion when just mentioning "dns".

**Comment by r10s** [comment]
i agree with @Simon-Laux.

> Add a long list of custom domains from all the users who approach us that they use this provider

i would definitely not do that. this would keep us busy over and over, for maybe only a handful of users using the provider.

so, for now, we should ignore them and spend the time with the tons of providers we can handle.

at some point, of course, we this can be handled by DNS, we can go for that.

**Comment by pabzm** [comment]
I agree with @Simon-Laux and @r10s, which results in not taking any action in the foreseeable future, thus I'm closing this.
