### ISSUE TITLE
re-add OK providers with the new data structure

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#76]
It should be a no-brainer to re-add the providers with `status: OK` from the old directory.

**Comment by r10s** [comment]
wondering, if we should add the following providers at all:

- with the status OK
- no special server settings needed
- no hints needed

at least from the app point of view, they are not needed and we can filter them out when generating the rust code.

but also in the database, they produce a lot of noise, as this will be easily a majority and will move the scope from the actually problematic ones.

**Comment by missytake** [comment]
what are the default settings which are tried if there is no info?

**Comment by r10s** [comment]
the app probes some common ports and also some username combinations.

**Comment by missytake** [comment]
@r10s which one? digging through https://github.com/deltachat/deltachat-core-rust/blob/master/src/configure/auto_outlook.rs and https://github.com/deltachat/deltachat-core-rust/blob/master/src/configure/auto_mozilla.rs I can't find them.

**Comment by missytake** [comment]
I'd just leave them in the database for now. We might want to provide that info in the future, that these providers just work. Even if it doesn't matter for the apps, because they will just try OK providers, there is no pressing need to delete them.

**Comment by Simon-Laux** [comment]
> @r10s which one? digging through https://github.com/deltachat/deltachat-core-rust/blob/master/src/configure/auto_outlook.rs and https://github.com/deltachat/deltachat-core-rust/blob/master/src/configure/auto_mozilla.rs I can't find them.

That are exactly the wrong files to look, `mod.rs` in this folder is the actual function that does everything. Those files are just what their names imply: parsing autoconfigure.xml files.

**Comment by r10s** [comment]
> at least from the app point of view, they are not needed and we can filter them out when generating the rust code.

i added a check to the update-script, providers with status=OK and without any additional information are skipped, so this is no longer an issue.

**Comment by adbenitez** [comment]
it is faster to try directly the know settings for OK providers rather than trying combinations which produced confusing error messages until the right combination is guessed, and in the case of nauta.cu the process of detecting the right configuration was painful slow

**Comment by r10s** [comment]
> it is faster to try directly the know settings for OK 

sure, but my point is about providers that are marked as OK _without_ specifying some known settings.
