### ISSUE TITLE
Last old providers

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#82]
There are some last providers left in old, after the current PRs are merged:

- [x] AOL - some preparation steps which should be tried out, but seem straightforward.
- [x] bitmessage.ch - seems like they shut down? their website has broken HTTPS.
- [x] fastmail.com - needs an app-specific password, should be tried out.
- [x] protonmail - broken. no IMAP. the IMAP bridge seems to be broken, too? do we even want to recommend such a hack?
- [x] t-online - needs an app-specific password, should be tried out.

**Comment by pabzm** [comment]
@missytake If you'd rather not work on this, re-assign this to me, please.
