### ISSUE TITLE
add mailo.com [request from forum]

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/provider-db#89]
https://support.delta.chat/t/providers-add-mailo/782

Looks like it works out of the box except when 2fa is activated an app-password is required. (from the post)

Maybe we should add an `after_failed_login` hint that hints that you need an app-password for such 2fa providers?

**Comment by r10s** [comment]
> Maybe we should add an after_failed_login hint that hints that you need an app-password for such 2fa providers?

why not say it before? 

however, anyway, for now, we should not add more things to the ui-part and to the api of the provider-db. we should implement the current state on all platform first to make some overall progress. of course, we can collect ideas etc, and if things are missing for many providers, we can think that over on the next iteration.

**Comment by Simon-Laux** [comment]
> why not say it before?

because that way less people see it when they don't have 2fa.
