### ISSUE TITLE
AOL

### ISSUE THREAD

**Issue by missytake** [deltachat/provider-db#91]
I failed to login to a fresh aol.com account with Delta Chat.

It's not helping that the AOL website is hanging a LOT.

Anyway, setting it up with thunderbird worked. This also showed that the info on https://help.aol.com/articles/download-your-email-from-aol-mail-with-imap is further outdated - the imap server is imap.aol.com, not export.imap.aol.com.

**Comment by pabzm** [comment]
I don't think having this provider in our db is worth the effort it apparently takes. How about dropping it?

**Comment by missytake** [comment]
They seem to have quite many users: https://expandedramblings.com/index.php/aol-statistics/

I think most of what it needs can be copy-pasted from yandex. If I'm the only one who wants to add support for AOL, then let's just drop it...

**Comment by missytake** [comment]
Ah right, we need to ask them for an extra client_id. Then let's drop it.

**Comment by missytake** [comment]
It seems that you can disable the two-step-login and can then use AOL more easily: https://support.postbox-inc.com/hc/en-us/articles/202200100-Email-Settings-for-AOL-Mail

See https://github.com/deltachat/deltachat-core-rust/issues/1294#issuecomment-590005858

I'll test it out.
