### ISSUE TITLE
add hostsharing.net

### ISSUE THREAD

**Issue by scoid** [deltachat/provider-db#95]
## Basic information (please modify and submit) 

**domain(s)**: example.hostsharing.net 

**website of provider**: https://www.hostsharing.net 

**works without preps**: YES

These three points are already useful enough to submit.

But if you can please provide more information below. 

### following preparations from the provider side (please add links if you can): 

- [ ] setting a per-app password 
- [ ] setting an option in provider's web interface 
- [ ] other: please describe 

### following advanced settings need to be set

neccessary manually typed advanced settings:

    smtp-server: example.hostsharing.net
    smtp-port: 587
    smtp-security: STARTTLS
    imap-server: example.hostsharing.net
    imap-port: 143
    imap-security: STARTTLS

### provider is funded by 
- [ ] advertisements 
- [X] recurring payments 
- [ ] donations 
- [x] private/pro-bono for friends 

## other comments 

green webhosting coop with servers in Germany

**Comment by missytake** [comment]
Looks like a cool provider, but do they offer email for domains apart from custom domains? For now we decided not to include custom domain providers in the DB.

Like, do they offer user@hostsharing.net addresses for all their customers?

**Comment by scoid** [comment]
> Looks like a cool provider, but do they offer email for domains apart from custom domains?

_No_, but obviously members building their business upon the coops server system (can) do it, like with any other provider.

>  Like, do they offer user@hostsharing.net addresses for all their customers?

_No_, every member can can book packages and gets a **subdomain** xyz00.hostsharing.net for which exist e-mail accounts and then of course any other arbitrary domain which is free.

**Comment by hpk42** [comment]
On Fri, Feb 07, 2020 at 04:24 -0800, Stephan Schildberg wrote:
> > Looks like a cool provider, but do they offer email for domains apart from custom domains?
> 
> _No_, but obviously members building their business upon the coops server system (can) do it, like with any other provider.

Can one do a particular DNS query to find out if a mail domain is hosted via hostsharing? 
could you maybe provide two examples of domains using hostsharing.net?

**Comment by scoid** [comment]
> could you maybe provide two examples of domains using hostsharing.net?

https://genossenschaftsgruendung.de/
https://www.itad.de

**Comment by missytake** [comment]
This hoster does not really fit into our scope, as explained. It does not offer a mail server on its own. 

If one of its customers is a dedicated mail provider and offers mail services to its users, we can add the mail server of the hostsharing customer to our database. In such a case, please open a new issue. But hostsharing itself is out of scope.

**Comment by hpk42** [comment]
I contacted hostsharing.net to see how we can get their hosted domains to be signalled as "Ok"  during account setup.

**Comment by missytake** [comment]
> I contacted hostsharing.net to see how we can get their hosted domains to be signalled as "Ok" during account setup.

Ist there anything new on that? Otherwise I would close this, and reopen only when we support custom domains.

**Comment by scoid** [comment]
Please close it. I recommend it to members of the hostsharing  coop who might be able to be in the role of a mail provider.
