### ISSUE TITLE
Will DC work with a Mailfence email?

### ISSUE THREAD

**Issue by DontUseGithub** [deltachat/provider-db#98]
Thank you.

**Comment by missytake** [comment]
Apparently not with a free account. Delta Chat needs IMAP access, and this is only available for paid accounts. Do you have a paid account and can try this out? https://blog.mailfence.com/pop3-vs-imap-vs-exchange-activesync/

**Comment by DontUseGithub** [comment]
Unfortunately I only have a free account. Thanks for checking that out, I really appreciate it.

**Comment by missytake** [comment]
With a free account it doesn't work:

![Screenshot_2020-02-14_17-40-23](https://user-images.githubusercontent.com/57442838/74550175-3ba78100-4f51-11ea-90bd-e0aabd04fe25.png)

Is this worth a BROKEN entry? That might scare users with paid plans. I'm a bit uncomfortable with adding a PREPARATION entry, if this would involve instructing users to pay for an offer somewhere. Other opinions?

**Comment by r10s** [comment]
if the thing works without further restrictions (some os only etc.), i think PREPARATION is fine here.

**Comment by missytake** [comment]
Well, without being able to try it out, I would close this issue for now.
