### ISSUE TITLE
ProtonMail needs better text

### ISSUE THREAD

**Issue by hpk42** [deltachat/provider-db#99]
https://providers.delta.chat/protonmail only says "it's broken".  Better to say it doesn't support the standard e-mail server protocols (IMAP and SMTP) ... maybe also read up on what ProtonMail themselves say. (there might be chances to get it to work on Desktop through the PRotonMail bridge).

**Comment by r10s** [comment]
the IMAP and SMTP bridge has so many limitations, that the decision was at some point to say that it is broken for the use with Delta Chat.
